apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: tweek
  name: management
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
      - name: management
        image: soluto/tweek-management
        ports:
        - containerPort: 3000
        env:
        - name: GIT_PUBLIC_KEY_PATH
          value: /run/secrets/tweek-git/tweek_ssh_public_key
        - name: GIT_PRIVATE_KEY_PATH
          value: /run/secrets/tweek-git/tweek_ssh_private_key
        - name: GIT_USER
          value: git
        - name: GIT_URL
          value: ssh://git@git/tweek/repo
        - name: VALIDATION_URL
          value: http://api/validation  
        volumeMounts:
        - name: git-keys
          mountPath: /run/secrets/tweek-git
      volumes:
        - name: git-keys
          secret:
            secretName: tweek-git
            defaultMode: 0600
---
kind: Service
apiVersion: v1
metadata:
  namespace: tweek
  name: management
spec:
  selector:
    app: management
  ports:
    - port: 3000
      targetPort: 3000