apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: tweek
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  namespace: tweek
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379